#!/usr/bin/env python3
"""Create or refresh ~/.hermes/roster.yaml mapping workflow roles to profiles.

Usage:
  setup_roster.py [--force] [--roster role=profile ...]
Non-interactive when --roster covers the required roles; otherwise prompts
with defaults derived from existing profiles. Remaining optional roles are
filled with sensible aliases so the workflow works immediately.
"""
import os
import argparse
import sys
from pathlib import Path

H = Path(os.environ.get('HERMES_HOME', str(Path.home() / '.hermes')))
REPO_ROSTER = Path(__file__).resolve().parents[1] / 'roster.yaml'

REQUIRED = ['coordinator', 'implementer', 'reviewer', 'verifier', 'security_reviewer']
ALIASES = {
    'planner': 'implementer',
    'researcher': 'implementer',
    'spike_explorer': 'implementer',
    'designer': 'implementer',
    'release_engineer': 'implementer',
    'security_tester': 'security_reviewer',
    'auditor': 'coordinator',
    'administrator': 'coordinator',
}
ROLE_ORDER = ['coordinator', 'researcher', 'spike_explorer', 'designer', 'planner',
              'implementer', 'release_engineer', 'reviewer', 'verifier',
              'security_reviewer', 'security_tester', 'auditor', 'administrator']
ROLE_NOTES = {
    'coordinator': 'routes work, owns final reports and PR content',
    'researcher': 'external facts and sourced briefs',
    'spike_explorer': 'disposable feasibility spikes',
    'designer': 'product/UX/accessibility design',
    'planner': 'architecture, plans, ADRs',
    'implementer': 'backend/frontend/full-stack implementation',
    'release_engineer': 'CI/CD, containers, release readiness',
    'reviewer': 'independent frozen-diff code review',
    'verifier': 'QA, regression, release evidence',
    'security_reviewer': 'read-only security analysis',
    'security_tester': 'authorization-gated active validation',
    'auditor': 'scheduled proactive audits',
    'administrator': 'administrative workflow',
}


def existing_profiles():
    root = H / 'profiles'
    return sorted(p.name for p in root.iterdir() if p.is_dir()) if root.is_dir() else []


def is_placeholder(roster):
    vals = {v.strip() for v in roster.values()}
    return not vals or any(v.startswith('your-') for v in vals)


def read_roster(path):
    roster, section = {}, None
    if not path.is_file():
        return roster
    for line in path.read_text().splitlines():
        if line.strip() == 'roles:':
            section = 'roles'
            continue
        if section == 'roles' and line.startswith(' ') and ':' in line:
            k, v = line.strip().split(':', 1)
            roster[k.strip()] = v.strip().split('#')[0].strip()
    return roster


def prompt(role, profiles, default):
    note = ROLE_NOTES.get(role, '')
    print(f"  {role} ({note})")
    print(f"    available: {', '.join(profiles)}")
    while True:
        ans = input(f"    profile for {role} [{default}]: ").strip()
        if not ans:
            ans = default
        if ans in profiles:
            return ans
        print(f"    '{ans}' is not an existing profile — pick from the list or Ctrl-C to abort.")


def write_roster(roster):
    lines = ['# Role -> Hermes profile mapping for the delivery workflow.',
             '# Generated by setup_roster.py — edit freely and re-run install.sh.', '']
    lines.append('roles:')
    for role in ROLE_ORDER:
        lines.append(f'  {role}: {roster.get(role, "")}  # {ROLE_NOTES[role]}')
    body = '\n'.join(lines) + '\n'
    target = H / 'roster.yaml'
    target.write_text(body)
    REPO_ROSTER.write_text(body)
    return target


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--force', action='store_true', help='rewrite even if a real roster exists')
    ap.add_argument('--roster', action='append', default=[], metavar='ROLE=PROFILE',
                    help='role=profile assignment (repeatable; bare role=profile args also accepted)')
    ap.add_argument('pairs', nargs='*', metavar='ROLE=PROFILE',
                    help='role=profile assignments without the flag')
    args, _unknown = ap.parse_known_args()
    args.roster = args.roster + args.pairs

    current = read_roster(H / 'roster.yaml')
    if current and not is_placeholder(current) and not args.force:
        print('roster exists and looks configured — nothing to do (use --force to redo)')
        return 0

    profiles = existing_profiles()
    if not profiles:
        print('ERROR: no profiles found under ~/.hermes/profiles — create your bots first')
        return 1

    given = {}
    for item in args.roster:
        if '=' not in item:
            print(f"ERROR: --roster expects ROLE=PROFILE, got {item!r}")
            return 1
        role, profile = item.split('=', 1)
        given[role.strip()] = profile.strip()

    for role, profile in given.items():
        if profile not in profiles:
            print(f"ERROR: profile {profile!r} for role {role!r} not found in ~/.hermes/profiles")
            return 1

    roster = dict(given)
    missing = [r for r in REQUIRED if r not in roster]
    if missing:
        if not sys.stdin.isatty():
            print('ERROR: non-interactive run missing required roles: ' + ', '.join(missing))
            print('       rerun with: ' + ' '.join(f'--roster {r}=<profile>' for r in missing))
            return 1
        print('Roster setup — 5 questions, Enter accepts the default:')
        defaults = {
            'coordinator': 'default' if 'default' in profiles else profiles[0],
            'implementer': given.get('coordinator', profiles[0]),
            'reviewer': given.get('implementer', profiles[0]),
            'verifier': given.get('reviewer', given.get('implementer', profiles[0])),
            'security_reviewer': given.get('reviewer', given.get('implementer', profiles[0])),
        }
        for role in missing:
            roster[role] = prompt(role, profiles, defaults[role])

    for role, alias in ALIASES.items():
        if role not in roster:
            roster[role] = roster.get(alias, roster['implementer'])

    target = write_roster(roster)
    print(f'roster written: {target}')
    aliased = ', '.join(f'{r}->{roster[r]}' for r in ALIASES if roster.get(r))
    print(f'optional roles aliased (edit {target} to specialize): {aliased}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
